/*
Enter your query here.
*/
select CITY, min(LENGTH(CITY))
 FROM STATION 
 GROUP BY CITY 
 ORDER BY LENGTH(CITY), CITY
 LIMIT 1;
SELECT CITY, max(LENGTH(CITY))
 FROM STATION
  GROUP BY CITY
   ORDER BY LENGTH(CITY) DESC, CITY
   LIMIT 1;